### ISSUE TITLE
Missing artifact com.byoskill.spring.cqrs:spring-cqrs-module:jar:1.0.6

### ISSUE THREAD

**Issue by kazupooot** [sleroy/spring-cqrs-arch#1]
Hi, when I am using maven, I am getting this error.

`Missing artifact com.byoskill.spring.cqrs:spring-cqrs-module:jar:1.0.6`

I added this on my pom dependency. 

```
<dependency>
  <groupId>com.byoskill.spring.cqrs</groupId>
    <artifactId>spring-cqrs-module</artifactId>
    <version>1.0.6</version>
</dependency>
```

**Comment by sleroy** [comment]
Hi,

The module is stored on JCenter: On the page below, you will find instruction about how to setup your project.

https://bintray.com/sleroy/maven/spring-cqrs-module
